/**
 * After dark: flirty and intimate, for couples who have BOTH switched it on
 * (18+). Suggestive, never explicit.
 *   2 options: [a, b] or [a, b, prompt]
 *   4 options: [prompt, a, b, c, d]
 * Ids are positions ("ad-0", ...): only ever append.
 */
export const AFTER_DARK: Array<[string, string] | [string, string, string] | [string, string, string, string, string]> = [
  ['Slow kisses', 'Stolen kisses'],
  ['Lights on', 'Lights off'],
  ['Morning cuddles', 'Midnight cuddles'],
  ['Flirty texts', 'Flirty voice notes'],
  ['What’s the most attractive thing I do without realising?', 'Laughing', 'Concentrating', 'Talking about what I love', 'Looking at you'],
  ['Candles', 'Fairy lights', 'Set the mood with…'],
  ['When we finally meet, the first kiss should be…', 'Right at the airport', 'Somewhere private', 'Slow and cinematic', 'Before we even say hi'],
  ['Forehead kisses', 'Neck kisses'],
  ['Which of my looks gets you most?', 'Dressed up', 'Just woken up', 'In your hoodie', 'Fresh out of the shower'],
  ['Tease', 'Be teased'],
  ['Best place for a secret kiss?', 'In the rain', 'In a lift', 'Under a blanket', 'In the back of a cab'],
  ['Take the lead', 'Follow the lead'],
  ['When we cuddle, I love…', 'My hair being played with', 'My back being rubbed', 'Being held tight', 'Holding hands'],
  ['Bubble bath together', 'Shower together'],
  ['What makes a text flirty for you?', 'A compliment', 'A hint', 'A photo', 'Something about later'],
  ['Give a massage', 'Get a massage'],
  ['A perfect night in has…', 'Candles and music', 'A movie we don’t watch', 'A long bath', 'No plans at all'],
  ['Romantic', 'Playful', 'Tonight I’m feeling…'],
  ['Goodnight kisses should be…', 'Soft', 'Slow', 'Lots of little ones', 'One long one'],
  ['Whisper it', 'Say it out loud'],
  ['What do you want more of from me?', 'Compliments', 'Flirting', 'Touch', 'Late-night talks'],
  ['Slow dance in the kitchen', 'Kiss against the wall'],
  ['Favourite place to kiss me?', 'Lips', 'Neck', 'Forehead', 'Hands'],
  ['Flirty photos are…', 'Very welcome', 'Nice once in a while', 'Not my thing, words please', 'Only in person'],
  ['What do you miss most at night?', 'Your warmth', 'Your kisses', 'Your voice up close', 'Falling asleep together'],
  ['Hotel weekend', 'Beach at night'],
  ['The most attractive quality?', 'Confidence', 'Kindness', 'Humour', 'Brains'],
  ['What puts you in the mood fastest?', 'Words', 'Touch', 'A look', 'Music'],
  ['Silk sheets', 'Soft cotton'],
  ['Romance should be…', 'Totally unplanned', 'Hinted at all day', 'Planned but secret', 'Fully planned together'],
  ['What would you wear to surprise me?', 'Something red', 'Something black', 'Something of yours', 'Just a smile'],
  ['Eye contact', 'Eyes closed', 'While kissing:'],
  ['Our chemistry is…', 'Fireworks', 'A slow burn', 'Warm and cozy', 'Off the charts'],
  ['The best kind of kiss?', 'Slow', 'Playful', 'Deep', 'Unexpected'],
  ['Mountains with a fireplace', 'A villa by the sea', 'Next romantic getaway:'],
  ['During a long hug, I’m thinking…', 'Nothing, just bliss', 'You smell so good', 'Don’t let go', 'What happens next'],
  ['Wake up tangled', 'Wake up to breakfast'],
  ['The way I say your name that gets you?', 'Softly', 'Teasingly', 'When I’m laughing', 'When I’m missing you'],
  ['Couples massage', 'Slow dancing lesson', 'Try together:'],
  ['How do you feel about teasing?', 'I love to tease', 'I love being teased', 'Both', 'Keep it sweet'],
  ['Golden hour', 'Midnight', 'Most romantic time?'],
  ['How long could we kiss without stopping?', 'A minute', 'Ten minutes', 'Until we’re late', 'Forever'],
  ['Sweet talk', 'Dirty jokes'],
  ['What do you notice first when I dress up?', 'My eyes', 'My lips', 'The outfit', 'The perfume'],
  ['Hand on the knee', 'Arm around the waist', 'In public:'],
  ['The first thing you’d do if I were there right now?', 'Kiss you', 'Hold you', 'Pull you onto the couch', 'Just stare'],
  ['Serenade me', 'Write me a poem'],
  ['Which compliment lands best?', 'You’re gorgeous', 'You drive me crazy', 'I can’t stop thinking about you', 'You’re mine'],
  ['Spend the night talking', 'Spend the night not talking'],
  ['Your flirting style?', 'Subtle hints', 'Bold and direct', 'Cheesy lines', 'All eyes'],
  ['Perfume', 'Natural scent', 'What gets me:'],
  ['Sleep in your shirt', 'Sleep in nothing'],
  ['Which would make you blush most?', 'A long look', 'A whisper in your ear', 'A compliment in public', 'A hand in yours'],
  ['Kiss in the rain', 'Kiss by the fire'],
  ['A date that ends at…', 'The door with one kiss', 'The couch', 'Breakfast together', 'Sunrise'],
  ['Morning romance', 'Late-night romance'],
  ['What would you plan for our first night back together?', 'Dinner, then home', 'Room service and a movie', 'A long bath', 'No plans, just us'],
  ['Flirt over text', 'Flirt over call'],
  ['What do you love about my voice?', 'When it’s sleepy', 'When I laugh', 'When I whisper', 'When I say I love you'],
  ['Blindfold taste test', 'Slow dance with eyes closed', 'Game night idea:'],
  ['Make the first move', 'Wait for the first move'],
  ['A kiss that says…', 'I missed you', 'I want you', 'I’m sorry', 'Goodnight'],
  ['Cuddle facing each other', 'Big spoon, little spoon'],
  ['Where should my hands be when we hug?', 'Around your waist', 'Around your neck', 'In your hair', 'In your back pockets'],
  ['Lingerie', 'Pyjamas', 'Gift idea:'],
  ['Your ideal “come over” text?', 'I miss you', 'Are you busy?', 'I have a surprise', 'Just a single emoji'],
  ['Hickeys', 'No marks'],
  ['What’s your weak spot?', 'Neck', 'Ears', 'Lips', 'Hands'],
  ['Skinny dipping', 'Hot tub', 'Late-night swim:'],
  ['How do you like to be woken up?', 'With kisses', 'With breakfast', 'With cuddles', 'Let me sleep'],
  ['Mirror selfie', 'Candid in bed', 'A photo for my eyes only:'],
  ['Which song sets the mood?', 'Something slow and old', 'A sultry new track', 'Bollywood romance', 'Silence is better'],
  ['Undressed by you', 'Undress for you'],
  ['Best way to end an argument?', 'A long hug', 'A kiss', 'Laughing it off', 'Making up properly'],
  ['Bath with candles', 'Bed with fairy lights'],
  ['What do you think about when you miss me?', 'Your smile', 'Your hands', 'Your lips', 'Your laugh'],
  ['Wear my perfume', 'Wear my shirt'],
  ['A love note hidden…', 'In your bag', 'Under your pillow', 'On the mirror', 'In your pocket'],
  ['Soft and slow', 'Wild and fun'],
  ['What’s your favourite part of kissing me?', 'The first second', 'When we smile mid-kiss', 'When it gets deeper', 'The goodbye kiss'],
  ['Honeymoon suite', 'Treehouse'],
  ['How do you want to be missed?', 'Sweet messages', 'Flirty messages', 'Long calls', 'Countdown to seeing me'],
  ['Kiss my neck', 'Kiss my hands'],
  ['A long-distance thing that feels closest?', 'Falling asleep on call', 'Flirty voice notes', 'Wearing each other’s clothes', 'Planning our first night back'],
  ['Wine and music', 'Chai and blankets', 'Night in:'],
  ['Where would you take me for a surprise night away?', 'The hills', 'The beach', 'A fancy hotel in the city', 'Somewhere with no network'],
  ['Show me', 'Tell me'],
  ['What makes you feel most wanted?', 'When I can’t stop looking', 'When I pull you close', 'When I say it', 'When I plan for us'],
  ['Cuddle all night', 'Need my own space'],
  ['The best thing to hear before sleep?', 'I love you', 'I miss you', 'Dream of me', 'Wish you were here'],
  ['Candlelit dinner', 'Breakfast in bed'],
  ['What would you whisper to me right now?', 'I miss you', 'Come here', 'You’re trouble', 'Guess'],
  ['Kiss hello', 'Kiss goodbye', 'The better kiss?'],
  ['Which of my habits is secretly cute?', 'Biting my lip', 'Playing with my hair', 'Stealing your food', 'Humming'],
  ['Tickle fight', 'Pillow fight'],
  ['First night back, we fall asleep…', 'Tangled up', 'Talking till 4 am', 'Halfway through a movie', 'We don’t'],
  ['Quiet and close', 'Loud and laughing'],
  ['Where do you want a kiss right now?', 'Forehead', 'Cheek', 'Lips', 'Somewhere secret'],
  ['Matching pyjamas', 'No pyjamas'],
  ['The most romantic thing I could do?', 'Show up unannounced', 'Write you a letter', 'Plan a whole day', 'Slow dance anywhere'],
];
