/**
 * This or That: two quick options. [optionA, optionB, prompt?]
 * Card ids are positions ("tot-0", "tot-1", ...), so only ever append to
 * this list. Never reorder or delete, or old letters will point at the
 * wrong question.
 */
export const THIS_OR_THAT: Array<[string, string] | [string, string, string]> = [
  ['Tea', 'Coffee'],
  ['Mountains', 'Beaches'],
  ['Sunrise', 'Sunset'],
  ['Texts', 'Voice notes'],
  ['Early bird', 'Night owl'],
  ['Instant noodles', 'Fries', 'Midnight snack?'],
  ['Tropical island', 'Snowy mountain town'],
  ['Rom-com', 'Thriller'],
  ['Window seat', 'Aisle seat'],
  ['Dogs', 'Cats'],
  ['Rainy season', 'Winter'],
  ['Street food', 'Fancy dinner'],
  ['Road trip', 'Flight'],
  ['Cook together', 'Order in'],
  ['Books', 'Podcasts'],
  ['Plan everything', 'Go with the flow'],
  ['Big party', 'Small dinner'],
  ['Hoodie', 'Blanket'],
  ['Good-morning call', 'Goodnight call'],
  ['Pizza', 'Tacos'],
  ['Sweet', 'Savoury'],
  ['Handwritten letter', 'Surprise gift'],
  ['Board games', 'Video games'],
  ['Ice cream', 'Warm pie'],
  ['Old songs', 'New songs'],
  ['Dance', 'Sing', 'At a wedding, you…'],
  ['Cuddle on the couch', 'Walk outside'],
  ['Movie at home', 'Movie in a theatre'],
  ['Dumplings', 'Spring rolls'],
  ['Hot coffee', 'Iced coffee'],
  ['Beach house', 'Cabin in the woods'],
  ['Surprise me', 'Plan it together'],
  ['Stay in pyjamas', 'Dress up'],
  ['Texting all day', 'One long call'],
  ['Sushi', 'Burgers'],
  ['Train journey', 'Road trip'],
  ['Museums', 'Markets'],
  ['Dessert first', 'Dessert last'],
  ['Sleep in', 'Early start'],
  ['Selfies', 'Candids'],
  ['Fairy lights', 'Candles'],
  ['Watching sports', 'Playing sports'],
  ['Morning workout', 'Evening walk'],
  ['Extra spicy', 'Mild please'],
  ['Mango', 'Strawberries'],
  ['Paris', 'Tokyo'],
  ['Desert road trip', 'Rainforest trek'],
  ['Fireworks', 'Fairground rides'],
  ['Roadside diner', 'Rooftop café'],
  ['Tea in a fancy cup', 'Tea in a giant mug'],
  ['Crossword', 'Sudoku'],
  ['Rainy day in', 'Sunny day out'],
  ['Horror movie', 'Comedy'],
  ['Karaoke', 'Quiz night'],
  ['Late-night drive', 'Early-morning walk'],
  ['Postcards', 'Polaroids'],
  ['Pets', 'Plants'],
  ['Fast replies', 'Thoughtful replies'],
  ['Emojis', 'Stickers'],
  ['Adventure', 'Comfort'],
  ['Surprise visit', 'Planned visit'],
  ['Flowers', 'Snacks', 'Airport pickup with…'],
  ['Croissant', 'Bagel'],
  ['Oatmeal', 'Cereal'],
  ['Pasta', 'Rice bowl'],
  ['Doughnuts', 'Cookies'],
  ['Teleport to each other', 'Pause time together', 'Pick a superpower:'],
  ['Visit the past', 'Peek at the future'],
  ['Swim', 'Hike'],
  ['Cook', 'Clean'],
  ['Small wedding', 'Huge wedding'],
  ['City flat', 'House with a garden'],
  ['Dishes', 'Laundry'],
  ['Paper books', 'Kindle'],
  ['Sing in the shower', 'Dance in the kitchen'],
  ['Sweater weather', 'Beach weather'],
  ['Chocolate', 'Vanilla'],
  ['Brownie', 'Cheesecake'],
  ['Hot shower', 'Cold shower'],
  ['Ocean', 'Lake'],
  ['Stars', 'Moon'],
  ['Silence', 'Background music'],
  ['Video call', 'Voice call'],
  ['Countdowns', 'Surprises', 'Before we meet:'],
  ['Socks on', 'Socks off', 'In bed:'],
  ['Left side of the bed', 'Right side of the bed'],
  ['One big trip', 'Lots of small trips'],
  ['Cake', 'Pudding'],
  ['Pancakes', 'Waffles'],
  ['Salted popcorn', 'Caramel popcorn'],
  ['Top bunk', 'Bottom bunk'],
  ['Snow', 'Sand'],
  ['Rewatch a favourite', 'Start something new'],
  ['Harry Potter', 'Lord of the Rings'],
  ['Marvel', 'DC'],
  ['Love songs', 'Breakup songs'],
  ['Jazz', 'Lo-fi'],
  ['Smoothie', 'Lemonade'],
  ['Bookstore date', 'Café date'],
  ['Stargazing', 'Sunrise hike'],
  ['Cozy night in', 'Night out'],
  ['Sunday brunch', 'Sunday nap'],
  ['Matching outfits', 'Matching mugs'],
  ['Cute nicknames', 'Funny nicknames'],
  ['Words', 'Actions', 'Love is mostly…'],
  ['Pineapple on pizza', 'Never pineapple'],
  ['Ketchup', 'Mayo'],
  ['Autumn', 'Spring'],
  ['Hugs', 'Kisses'],
  ['Morning texts', 'Midnight texts'],
  ['Spontaneous', 'Organised'],
  ['Long hugs', 'Hand-holding'],
  ['Cooking show', 'Travel show'],
  ['Old-town walk', 'Theme park'],
  ['Sea-facing room', 'Mountain-view room'],
  ['Cold drink', 'Hot drink'],
  ['Ride in the rain', 'Watch the rain'],
  ['Birthday at midnight', 'Birthday at breakfast'],
  ['Photo album', 'Photo wall'],
  ['Stay up late talking', 'Wake up early together'],
];
