/**
 * Daily Connect: the deeper last card of the day. Four options plus an
 * optional one-line note to your partner. [prompt, a, b, c, d]
 * Ids are positions ("con-0", ...): only ever append.
 */
export const CONNECT: Array<[string, string, string, string, string]> = [
  ['Today, I feel closest to you when…', 'You text first', 'We’re on a call', 'I see your photos', 'I think about our plans'],
  ['What would help me most this week?', 'More calls', 'A little surprise', 'Some patience', 'A plan for our next meet'],
  ['When I go quiet, it usually means…', 'I’m tired', 'I’m thinking', 'Something’s bothering me', 'I need a hug'],
  ['Something I want us to do more of:', 'Laugh', 'Plan the future', 'Talk about feelings', 'Be silly'],
  ['The hardest part of the distance right now:', 'Not being able to touch', 'Time zones', 'Missing little moments', 'Not knowing when we’ll meet'],
  ['I knew I liked you when…', 'We had our first long talk', 'You did something small and kind', 'You made me laugh', 'I just knew'],
  ['What makes a call feel good?', 'Long and slow', 'Short but often', 'Video, faces on', 'Falling asleep on it'],
  ['I feel most appreciated when you…', 'Notice little things', 'Say thank you', 'Make time for me', 'Brag about me'],
  ['What I’m most looking forward to:', 'Our next meet', 'Living together', 'Travelling together', 'Growing old together'],
  ['When we disagree, I need…', 'Time to cool off', 'To talk right away', 'Reassurance first', 'A hug before words'],
  ['My favourite message from you:', 'Good morning', 'Random memes', 'Voice notes', 'Long ones'],
  ['Our relationship feels like…', 'A cozy blanket', 'An adventure', 'A best friendship', 'A slow song'],
  ['How am I feeling about us today?', 'Really close', 'Pretty good', 'A little far', 'Missing you a lot'],
  ['What would make me feel more secure?', 'More check-ins', 'Plans for the future', 'Honest talks', 'Hearing you say it'],
  ['A little ritual I’d love us to have:', 'A goodnight call', 'A weekly movie', 'Sunday letters', 'A shared playlist'],
  ['What I love most about how you love me:', 'Your patience', 'Your humour', 'Your effort', 'Your honesty'],
  ['What do I need when I’m stressed?', 'Just listen', 'Distract me', 'Help me fix it', 'Just be there'],
  ['The memory of us I replay most:', 'Our first meet', 'A trip', 'A silly moment', 'A long talk'],
  ['We feel like a team when…', 'We solve problems together', 'We plan together', 'We cheer each other on', 'We have inside jokes'],
  ['Next time we meet, I first want to…', 'Hug for ages', 'Eat together', 'Go somewhere new', 'Sleep in together'],
  ['What I wish you understood better:', 'My work', 'My family', 'My moods', 'My dreams'],
  ['A goal I’d love us to work on:', 'Saving money', 'Getting fit', 'Learning something', 'Planning a move'],
  ['When I think about our future, I feel…', 'Excited', 'Calm', 'A bit nervous', 'Hopeful'],
  ['What does home mean to me?', 'A place', 'A person', 'A feeling', 'Family'],
  ['After a bad day, comfort looks like…', 'Talking it through', 'Jokes', 'Quiet company', 'Something to look forward to'],
  ['Something I’m proud of us for:', 'Making distance work', 'How we talk', 'How we’ve grown', 'How much we laugh'],
  ['How often do I want a deep talk?', 'Every day', 'Once a week', 'When it comes up', 'When something’s wrong'],
  ['Something I’d love to try together:', 'A class', 'A trip', 'A project', 'A new tradition'],
  ['What I value most in us:', 'Trust', 'Fun', 'Growth', 'Comfort'],
  ['When I miss you, I…', 'Look at our photos', 'Re-read our chats', 'Play our songs', 'Text you right away'],
  ['What makes me feel close when we’re far?', 'Watching things together', 'Sleeping on call', 'Sending photos', 'Playing games'],
  ['How do I prefer to hear hard things?', 'Straight away', 'Gently', 'In writing', 'In person'],
  ['What I want our weekends to feel like:', 'Busy and fun', 'Slow and restful', 'Full of calls', 'A bit of everything'],
  ['My favourite thing about talking to you:', 'You listen', 'You make me laugh', 'You’re honest', 'I can be myself'],
  ['What would make our next meet perfect?', 'No plans at all', 'A trip somewhere', 'Meeting each other’s people', 'Lots of good food'],
  ['What did I need more of this week?', 'Rest', 'Fun', 'Attention', 'Space'],
  ['One way you make my life better:', 'You make me laugh', 'You support me', 'You calm me down', 'You push me to grow'],
  ['Something I’ve been wanting to say:', 'Thank you', 'Sorry', 'I’m proud of you', 'I miss you'],
  ['Where I picture us in five years:', 'In the same city', 'Married', 'Travelling', 'Still figuring it out'],
  ['What makes me trust someone?', 'Consistency', 'Honesty', 'Keeping small promises', 'Time'],
  ['The part of our story I’d tell first:', 'How we met', 'The distance', 'Our first trip', 'The silly stuff'],
  ['How I like to celebrate milestones:', 'A special date', 'Gifts', 'A trip', 'A quiet moment'],
  ['A small thing you do that I love:', 'How you text', 'Your voice notes', 'How you remember things', 'How you say my name'],
  ['How I feel about our calls lately:', 'Just right', 'I want more', 'I want them deeper', 'I want more variety'],
  ['One free day together this week, we’d…', 'Go out', 'Stay in', 'Take a short trip', 'Cook and chill'],
  ['What worries me a little about us:', 'The distance', 'Timing', 'Our families', 'Nothing really'],
  ['What says “I love you” most to me:', 'Showing up', 'Remembering details', 'Saying it often', 'Making plans'],
  ['How you can support my goals this month:', 'Check in on them', 'Cheer me on', 'Give me space', 'Help me plan'],
  ['A family tradition I’d like us to keep:', 'Festival rituals', 'Big Sunday meals', 'Birthday customs', 'Something small and silly'],
  ['What I’d like more of in our chats:', 'Deep talks', 'Silly stuff', 'Plans', 'Flirting'],
  ['I feel understood when you…', 'Remember things', 'Ask questions', 'Don’t judge', 'Just get it'],
  ['How I want us to handle time apart:', 'Set call times', 'Go with the flow', 'Do things together online', 'Count down together'],
  ['The kindest thing you’ve done for me:', 'Stayed up for me', 'Surprised me', 'Backed a decision', 'Forgiven me'],
  ['A good day between us looks like…', 'Lots of texts', 'One great call', 'Watching something together', 'Laughing a lot'],
  ['How ready do I feel for our next big step?', 'Very ready', 'Getting there', 'Not yet', 'Depends on the step'],
  ['I feel most attractive when…', 'You compliment me', 'You look at me a certain way', 'I take care of myself', 'I feel loved'],
  ['Right now I’d thank you for…', 'Your patience', 'Your time', 'Your love', 'Your jokes'],
  ['One word for us this week:', 'Cozy', 'Busy', 'Far', 'Strong'],
  ['What helps me feel rested before we talk?', 'Eating first', 'A quick nap', 'Some alone time', 'Nothing, just you'],
  ['The best part of yesterday was…', 'Talking to you', 'Something at work or college', 'Time to myself', 'Friends or family'],
];
