/**
 * Know Me: questions about yourself, four options. You answer for yourself,
 * then guess what your partner picked. [prompt, a, b, c, d]
 * Ids are positions ("know-0", ...): only ever append.
 */
export const KNOW_ME: Array<[string, string, string, string, string]> = [
  ['After a long day, what do you reach for first?', 'A hot shower', 'Food', 'My phone', 'My bed'],
  ['Your comfort food on a bad day?', 'Instant noodles', 'Chocolate', 'Something from home', 'Ice cream'],
  ['What makes you feel most loved?', 'Kind words', 'Time together', 'Little gifts', 'Help with things'],
  ['Your ideal Sunday morning?', 'Sleeping in', 'A walk outside', 'A big breakfast', 'Lazy scrolling'],
  ['When you’re stressed, you usually…', 'Go quiet', 'Talk it out', 'Keep busy', 'Sleep it off'],
  ['Your karaoke pick?', 'A sad love song', 'A big pop banger', 'An old classic', 'I’m only there for snacks'],
  ['The chore you secretly don’t mind?', 'Cooking', 'Laundry', 'Dishes', 'Grocery runs'],
  ['Your dream holiday?', 'Snowy mountains', 'A tropical island', 'A big city', 'A quiet cottage'],
  ['A surprise day off. You…', 'Sleep', 'Binge a show', 'See friends', 'Finally do that hobby'],
  ['A surprise bonus. You spend it on…', 'Clothes', 'A gadget', 'A trip', 'Nothing, I save it'],
  ['Phone at 5%. You use it to…', 'Text me', 'Call family', 'Check work', 'Play one more song'],
  ['Your guilty-pleasure watch?', 'Reality TV', 'K-dramas', 'Anime', 'True crime'],
  ['Which smell takes you straight home?', 'Rain on soil', 'Something cooking at home', 'Incense', 'Fresh laundry'],
  ['How do you like to be cheered up?', 'A hug', 'Jokes', 'Food', 'A bit of space'],
  ['First thing you notice about someone?', 'Their smile', 'Their eyes', 'Their voice', 'How they treat people'],
  ['Your most-used emoji?', 'Crying laughing', 'A heart', 'Eye-roll', 'The skull'],
  ['Pick your superpower.', 'Read minds', 'Teleport', 'Pause time', 'Talk to animals'],
  ['Your ideal birthday?', 'A big party', 'A quiet dinner', 'A surprise trip', 'A lazy day'],
  ['What do you lose most often?', 'Keys', 'Earphones', 'Charger', 'Track of time'],
  ['At a wedding, you’re…', 'On the dance floor', 'At the food counter', 'Taking photos', 'Chatting with relatives'],
  ['Your non-negotiable morning thing?', 'Tea or coffee', 'A workout', 'Scrolling in bed', 'The snooze button'],
  ['Your hidden talent?', 'Cooking', 'Singing', 'Drawing', 'Doing impressions'],
  ['Childhood treat you’d still fight for?', 'Cookies', 'Chips', 'Candy', 'Chocolate bars'],
  ['Getting-ready music?', 'Pop hits', 'Old classics', 'Hip-hop', 'Lo-fi'],
  ['When you’re sick, you want…', 'To be left alone', 'Constant care', 'Soup and a movie', 'Lots of calls'],
  ['First thing you do in a new city?', 'Find good food', 'Wander around', 'See the landmarks', 'Shop'],
  ['Your texting style?', 'Long paragraphs', 'Many short texts', 'Voice notes', 'Mostly memes'],
  ['Which would you rather receive?', 'A handwritten letter', 'Flowers', 'A playlist', 'Food delivered'],
  ['Your role on a group trip?', 'The planner', 'The photographer', 'The DJ', 'The one who naps'],
  ['Favourite time of day?', 'Early morning', 'Afternoon', 'Evening', 'Late night'],
  ['Movie for us tonight?', 'A rom-com', 'A thriller', 'Something animated', 'An old classic'],
  ['Your ideal weather?', 'Cold and cozy', 'Rainy', 'Warm and sunny', 'A breezy evening'],
  ['How do you handle an argument?', 'Cool off first', 'Sort it out right away', 'Crack a joke', 'Write my thoughts down'],
  ['Your spending weakness?', 'Food', 'Clothes', 'Gadgets', 'Travel'],
  ['What would friends say you’re best at?', 'Listening', 'Making plans', 'Making people laugh', 'Giving advice'],
  ['Your sleeping position?', 'Starfish', 'Curled up', 'On my back', 'Hugging a pillow'],
  ['Which world would you move into?', 'Hogwarts', 'Middle-earth', 'A Ghibli film', 'The Marvel universe'],
  ['Your biggest pet peeve?', 'Loud chewing', 'Lateness', 'Being left on seen', 'Messy spaces'],
  ['Perfect pizza topping?', 'Pepperoni', 'Extra cheese', 'Loaded veggies', 'Mushrooms'],
  ['The gift you secretly love most?', 'Something handmade', 'Something I mentioned once', 'Something useful', 'An experience'],
  ['Where do you do your best thinking?', 'In the shower', 'On a walk', 'Right before sleep', 'On the commute'],
  ['Your café order?', 'Cappuccino', 'Iced coffee', 'Spiced tea', 'Hot chocolate'],
  ['Which celebration do you look forward to most?', 'The holidays', 'New Year’s Eve', 'My birthday', 'Our anniversary'],
  ['Rainy day plan?', 'Snacks and tea', 'A long nap', 'Dance in the rain', 'Movie marathon'],
  ['Your comfort rewatch?', 'Friends', 'The Office', 'An old romance', 'A Ghibli film'],
  ['How many alarms do you set?', 'Just one', 'Two or three', 'Five or more', 'None, I wake up on my own'],
  ['What would you name a pet?', 'A human name', 'A food name', 'Something grand', 'Something silly'],
  ['In a zombie apocalypse, you’re…', 'The leader', 'The medic', 'The one hiding', 'The first to go'],
  ['What kind of packer are you?', 'Over-packer', 'Last-minute packer', 'Cabin bag only', 'I always forget something'],
  ['What do you miss most when we’re apart?', 'Hugs', 'Eating together', 'Doing nothing together', 'Hearing you in person'],
  ['Your ideal date night?', 'Fancy dinner', 'Street food walk', 'Movie night in', 'Something adventurous'],
  ['Can’t sleep. You…', 'Scroll my phone', 'Read', 'Overthink', 'Put music on'],
  ['A chore you’d give away forever?', 'Dishes', 'Laundry', 'Bathroom cleaning', 'Cooking'],
  ['Your instant noodles style?', 'Plain', 'Loaded with veggies', 'Extra cheese', 'Soupy'],
  ['A hobby you’d love to learn?', 'An instrument', 'A language', 'Dance', 'Pottery'],
  ['How do you like birthday wishes?', 'At midnight', 'First thing in the morning', 'A surprise later', 'A big post'],
  ['Your kind of weekend?', 'Packed with plans', 'Totally lazy', 'Half and half', 'Away somewhere'],
  ['Last-minute trip pick?', 'Beach', 'Hills', 'A new city', 'Home to family'],
  ['How do you react to surprises?', 'Love them', 'Awkward but happy', 'I prefer a heads-up', 'Honestly, not a fan'],
  ['What fills your camera roll?', 'Screenshots', 'Food', 'Selfies', 'Sky and nature'],
  ['The app you open most?', 'WhatsApp', 'Instagram', 'YouTube', 'Spotify'],
  ['Good news! You first…', 'Tell everyone', 'Treat myself', 'Call you', 'Smile quietly'],
  ['Dessert pick?', 'Cheesecake', 'Brownie', 'Ice cream', 'Apple pie'],
  ['When you’re annoyed, you get…', 'Quiet', 'Loud', 'Sarcastic', 'Hungry'],
  ['Your home style?', 'Cozy and cluttered', 'Minimal', 'Plants everywhere', 'Colourful'],
  ['Your approach to deadlines?', 'Done early', 'Right on time', 'Last minute', 'Deadlines are suggestions'],
  ['Your drink at a party?', 'A mocktail', 'A soft drink', 'Something fancy', 'Just water'],
  ['What do you work best to?', 'Lo-fi', 'Silence', 'Podcasts', 'Loud playlists'],
  ['Weekend getaway pick?', 'Somewhere in the hills', 'A beach town', 'A historic old town', 'A resort to do nothing'],
  ['A song you love comes on. You…', 'Sing loudly', 'Dance', 'Turn it up', 'Send it to you'],
  ['Your favourite thing about your looks?', 'My smile', 'My eyes', 'My hair', 'My laugh'],
  ['When is your energy highest?', 'Morning', 'Afternoon', 'Evening', 'Midnight'],
  ['Dream job if money didn’t matter?', 'Artist', 'Traveller', 'Chef', 'Teacher'],
  ['Snack while watching something?', 'Popcorn', 'Chips', 'Nachos', 'Chocolate'],
  ['Weird food combo you love?', 'Chips in a sandwich', 'Noodles with ketchup', 'Fries in ice cream', 'Pickle with everything'],
  ['The perfect gift from me?', 'Something to wear', 'Something for my room', 'A day out together', 'A letter'],
  ['A cheap and cheerful date. We…', 'Do a street food crawl', 'Catch a movie', 'Get coffee and walk', 'Get flowers and chocolate'],
  ['How do you say sorry?', 'Straight up', 'With food', 'With a long message', 'With a hug'],
  ['What kind of friend are you?', 'The planner', 'The therapist', 'The comedian', 'The one who shows up'],
  ['What takes you the longest?', 'Choosing food', 'Getting ready', 'Picking a movie', 'Replying to texts'],
  ['Your 60th birthday?', 'Big family party', 'Somewhere new', 'A quiet day with you', 'Dancing all night'],
  ['Same city tomorrow. First thing?', 'Hug for an hour', 'Go on a date', 'Cook together', 'Do nothing together'],
  ['Favourite season?', 'Summer', 'Autumn', 'Winter', 'Spring'],
  ['Your small fear?', 'Spiders', 'Heights', 'Deep water', 'Being late'],
  ['First binge on a new app?', 'A thriller', 'A comedy', 'A documentary', 'Something romantic'],
  ['Favourite way to move?', 'Gym', 'Walking', 'A sport', 'Dancing'],
  ['Your shopping style?', 'In and out', 'Browse for hours', 'Online only', 'Avoid it'],
  ['Which would you want at home?', 'A big kitchen', 'A reading nook', 'A balcony garden', 'A home theatre'],
  ['How fast do you reply to texts?', 'Instantly', 'Within the hour', 'When I remember', 'Depends who it is'],
  ['Which would you rather win?', 'A trip', 'A car', 'A year of free food', 'A home makeover'],
  ['How do you feel about PDA?', 'Love it', 'Holding hands is plenty', 'Only when no one’s looking', 'Depends on my mood'],
  ['Your comfort sound?', 'Rain', 'Ocean waves', 'A fan whirring', 'Your voice'],
  ['First thing you check in the morning?', 'Messages', 'The time', 'The news', 'The weather'],
  ['Best thing about where you grew up?', 'The food', 'The people', 'The weather', 'The memories'],
  ['Which on-screen couple is most like us?', 'Noah and Allie', 'Jim and Pam', 'Carl and Ellie', 'Monica and Chandler'],
  ['Your favourite way to unwind?', 'A long bath', 'A long walk', 'A long nap', 'A long call'],
  ['How do you learn best?', 'Watching videos', 'Reading', 'Trying it myself', 'Someone showing me'],
  ['The one thing you won’t share?', 'My food', 'My blanket', 'My charger', 'My fries'],
  ['Perfect breakfast?', 'Pancakes', 'Eggs and toast', 'Fruit and yoghurt', 'Just coffee'],
  ['How are you in the mornings?', 'Love them', 'Fine after coffee', 'Barely alive', 'What are mornings?'],
  ['What do you want more of this year?', 'Travel', 'Rest', 'Money', 'Time with you'],
  ['Favourite compliment to get?', 'You’re funny', 'You’re kind', 'You look great', 'You’re smart'],
  ['What kind of old person will you be?', 'Grumpy but cute', 'Still partying', 'Gardening daily', 'Full of long stories'],
  ['Your dream ride?', 'A vintage car', 'A sports car', 'A big SUV', 'A motorbike'],
  ['What do you cook best?', 'Instant noodles', 'Eggs', 'A proper meal', 'I order like a pro'],
  ['You win the lottery. First move?', 'Quit my job', 'Book a trip', 'Buy a home', 'Tell no one'],
  ['Pick our song.', 'Something romantic', 'Something funny', 'An old classic', 'A song from our early days'],
  ['Your excuse to leave a party?', 'Early morning', 'Not feeling great', 'Plant emergency', 'I just vanish'],
  ['The room you live in?', 'Bedroom', 'Kitchen', 'Living room', 'Balcony'],
  ['Your tea?', 'Strong and sweet', 'Light, less sugar', 'With ginger', 'Not a tea person'],
  ['Long flight. You…', 'Sleep', 'Watch movies', 'Read', 'Chat to the next seat'],
  ['Your theme song would be…', 'Dramatic', 'Upbeat', 'Soft', 'Funny'],
  ['What do you want to hear more often?', 'That I’m doing well', 'That I’m loved', 'That I’m funny', 'That I’m attractive'],
  ['Your go-to sick-day food?', 'Rice porridge', 'Soup', 'Toast and tea', 'Whatever’s delivered fastest'],
  ['How do you like to fall asleep?', 'In silence', 'With music', 'With a show on', 'On a call with you'],
  ['Your photo pose?', 'Big smile', 'Peace sign', 'Serious face', 'Hiding from the camera'],
  ['Which would you rather skip forever?', 'Mornings', 'Traffic', 'Meetings', 'Laundry'],
  ['Your ideal way to spend the holidays?', 'Big family gathering', 'Travelling', 'Friends and food', 'Quiet and cozy'],
  ['The snack that’s always in your room?', 'Chips', 'Biscuits', 'Chocolate', 'Fruit'],
  ['On a long car ride, you’re…', 'Asleep', 'The DJ', 'In charge of snacks', 'Talking the whole way'],
];
